<script setup lang="ts">
  import {computed, onMounted, onUnmounted, ref, watch} from 'vue';
  import {useI18n} from 'vue-i18n';
  import {
    ArrowPathIcon,
    CheckIcon,
    CheckCircleIcon,
    ChevronRightIcon,
    ClockIcon,
    ClipboardDocumentIcon,
    DocumentArrowDownIcon,
    DocumentPlusIcon,
    ExclamationTriangleIcon,
    ListBulletIcon,
    MicrophoneIcon,
    PauseIcon,
    PlayIcon,
    SignalIcon,
    SparklesIcon,
    Square2StackIcon,
    StopIcon,
    UserGroupIcon,
    XMarkIcon,
  } from '@heroicons/vue/24/outline';
  import {Notice, TFile} from 'obsidian';

  import {usePlugin} from '../../composables/usePlugin';
  import {
    type AudioCaptureController,
    type AudioInputDevice,
    listAudioInputDevices,
    pcm16ChunksToWavBlob,
    startAudioCapture,
  } from '../../services/audioCapture';
  import {openObsidianNote} from '../../services/noteNavigation';
  import {
    classifyTranscriptionAvailabilityError,
    isTranscriptionVersionSupported,
    MINIMUM_TRANSCRIPTION_VERSION,
    type TranscriptionAvailabilityStatus,
  } from '../../services/transcriptionAvailability';
  import type {
    TranscriptionMarkKind,
    TranscriptionScene,
    TranscriptionSegment,
    TranscriptionStartOptions,
  } from '../../types';
  import MarkdownView from '../MarkdownView.vue';
  import RekaSelect from '../RekaSelect.vue';
  import RekaSwitch from '../RekaSwitch.vue';
  import WmDialog from '../WmDialog.vue';

  const plugin = usePlugin();
  const {t} = useI18n();
  const controller = plugin.transcription;
  const state = controller.state;
  const formatRecordDate = (time = Date.now()) => {
    const date = new Date(time);
    const pad = (value: number) => String(value).padStart(2, '0');
    return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())} ${pad(
      date.getHours(),
    )}:${pad(date.getMinutes())}`;
  };
  const createDefaultRecordTitle = (time = Date.now()) =>
    t('transcription.defaultRecordTitle', {date: formatRecordDate(time)});
  const startOptions = ref<TranscriptionStartOptions | null>(null);
  const audioDevices = ref<AudioInputDevice[]>([]);
  const setupStatus = ref<'checking' | 'ready' | TranscriptionAvailabilityStatus>('checking');
  const loading = ref(false);
  const starting = ref(false);
  const organizing = ref(false);
  const openingRecords = ref(false);
  const historyDialogOpen = ref(false);
  const historyItems = ref([...plugin.settings.transcriptionHistory]);
  const speakerDialogOpen = ref(false);
  const speakerSaving = ref(false);
  const assigningSpeakerSegmentId = ref('');
  const speakerNames = ref<Record<string, string>>({});
  const speakerMergeTargets = ref<Record<string, string>>({});
  const completionView = ref<'transcript' | 'summary'>('transcript');
  const initialRecordTitle = createDefaultRecordTitle();
  const form = ref({
    title: initialRecordTitle,
    scene: plugin.settings.transcription.defaultScene as TranscriptionScene,
    providerId: plugin.settings.transcription.defaultProviderId,
    deviceId: plugin.settings.transcription.defaultMicrophoneId,
    saveAudio: plugin.settings.transcription.saveAudio,
    speakerDiarization: false,
    speakerCount: '0',
    liveWriteToNote: false,
  });
  const microphoneTestStatus = ref<'idle' | 'recording' | 'complete' | 'error'>('idle');
  const microphoneTestLevel = ref(0);
  const microphoneTestSeconds = ref(0);
  const microphoneTestUrl = ref('');
  const microphoneTestError = ref('');
  const transcriptionStream = ref<HTMLElement | null>(null);
  const followLatestSegment = ref(true);
  let microphoneTestCapture: AudioCaptureController | null = null;
  let microphoneTestTimer = 0;
  let microphoneTestClock = 0;
  let streamScrollFrame = 0;
  let autoGeneratedTitle = initialRecordTitle;
  let lastCompletionNoticeRecordId = '';
  const workspaceEventRefs: unknown[] = [];
  const vaultEventRefs: unknown[] = [];

  const activeFile = ref(plugin.app.workspace.getActiveFile());
  const activeMarkdownPath = ref(
    activeFile.value instanceof TFile && activeFile.value.extension === 'md'
      ? activeFile.value.path
      : '',
  );
  const isActive = computed(() => controller.isActive);
  const isRecording = computed(() => state.status === 'recording');
  const isPaused = computed(() => state.status === 'paused');
  const hasCompletedTranscript = computed(() =>
    Boolean(state.completedDetail?.segments.some(segment => segment.text.trim())),
  );
  const hasGeneratedSummary = computed(() =>
    Boolean(state.completedDetail?.record.summary?.trim()),
  );
  const completedTranscript = computed(() => {
    const detail = state.completedDetail;
    if (!detail) return '';
    const transcript = detail.segments
      .filter(segment => segment.text.trim())
      .map(segment => {
        const speaker = segmentSpeakerLabel(segment);
        return `${formatDuration(segment.beginTimeMs || 0)}${speaker ? `  ${speaker}` : ''}  ${segment.text.trim()}`;
      })
      .join('\n\n');
    return `${detail.record.title}\n\n${transcript}`.trim();
  });
  const isCurrentNoteAlreadyWritten = computed(
    () =>
      state.liveNoteWriteStatus === 'completed' &&
      Boolean(activeMarkdownPath.value) &&
      state.liveNoteTargetPath === activeMarkdownPath.value,
  );
  const usesFixedLayout = computed(
    () => isActive.value || (state.status === 'completed' && Boolean(state.completedDetail)),
  );
  const canStart = computed(() =>
    Boolean(
      startOptions.value?.membership.canStart &&
        form.value.providerId &&
        (!form.value.liveWriteToNote || activeMarkdownPath.value) &&
        !starting.value,
    ),
  );
  const elapsed = computed(() => formatDuration(state.elapsedMs));
  const connectionLabel = computed(() =>
    t(`transcription.connection.${state.connectionStatus || 'idle'}`),
  );
  const statusLabel = computed(() => t(`transcription.status.${state.status}`));
  const setupMessage = computed(() => {
    if (setupStatus.value === 'checking') {
      return {
        title: t('transcription.compatibility.checkingTitle'),
        description: t('transcription.compatibility.checkingDesc'),
      };
    }
    if (setupStatus.value === 'not-running') {
      return {
        title: t('transcription.compatibility.notRunningTitle'),
        description: t('transcription.compatibility.notRunningDesc'),
      };
    }
    if (setupStatus.value === 'unsupported') {
      return {
        title: t('transcription.compatibility.unsupportedTitle'),
        description: t('transcription.compatibility.unsupportedDesc', {
          version: MINIMUM_TRANSCRIPTION_VERSION,
        }),
      };
    }
    return {
      title: t('transcription.compatibility.unavailableTitle'),
      description: t('transcription.compatibility.unavailableDesc'),
    };
  });
  const sceneOptions = computed(() =>
    ['meeting', 'class', 'interview', 'idea', 'other'].map(value => ({
      value,
      label: t(`transcription.scenes.${value}`),
    })),
  );
  const providerOptions = computed(() =>
    (startOptions.value?.providers || []).map(provider => ({
      value: provider.id,
      label: `${provider.name}${provider.modelName ? ` · ${provider.modelName}` : ''}`,
    })),
  );
  const currentProvider = computed(() =>
    startOptions.value?.providers.find(provider => provider.id === form.value.providerId),
  );
  const speakerCountOptions = computed(() => [
    {value: '0', label: t('transcription.speakerCountAuto')},
    ...Array.from({length: 9}, (_, index) => ({
      value: String(index + 2),
      label: t('transcription.speakerCountValue', {count: index + 2}),
    })),
  ]);
  const completedSpeakers = computed(() => {
    const speakers = new Map<
      string,
      {id: string; name: string; segmentCount: number; durationMs: number}
    >();
    for (const segment of state.completedDetail?.segments || []) {
      const id = String(segment.speakerId || '').trim();
      if (!id) continue;
      const name = segmentSpeakerLabel(segment);
      const durationMs = Math.max(
        0,
        Number(segment.endTimeMs || segment.beginTimeMs || 0) -
          Number(segment.beginTimeMs || 0),
      );
      const existing = speakers.get(id);
      if (existing) {
        existing.segmentCount += 1;
        existing.durationMs += durationMs;
        if (segment.speakerLabel?.trim()) existing.name = name;
      } else {
        speakers.set(id, {id, name, segmentCount: 1, durationMs});
      }
    }
    return [...speakers.values()].sort((a, b) => {
      const numberA = Number(a.id.match(/(\d+)$/)?.[1] || Number.MAX_SAFE_INTEGER);
      const numberB = Number(b.id.match(/(\d+)$/)?.[1] || Number.MAX_SAFE_INTEGER);
      return numberA - numberB || a.id.localeCompare(b.id);
    });
  });
  const microphoneOptions = computed(() => {
    const options = audioDevices.value.map((device, index) => ({
      value: device.deviceId,
      label: device.label || t('transcription.microphoneNumber', {number: index + 1}),
    }));
    if (!options.some(option => option.value === 'default')) {
      options.unshift({value: 'default', label: t('transcription.defaultMicrophone')});
    }
    return options;
  });

  function formatDuration(milliseconds: number) {
    const seconds = Math.max(0, Math.floor(milliseconds / 1000));
    const hours = Math.floor(seconds / 3600);
    const minutes = Math.floor((seconds % 3600) / 60);
    const remain = seconds % 60;
    return hours
      ? `${String(hours).padStart(2, '0')}:${String(minutes).padStart(2, '0')}:${String(
          remain,
        ).padStart(2, '0')}`
      : `${String(minutes).padStart(2, '0')}:${String(remain).padStart(2, '0')}`;
  }

  const segmentSpeakerLabel = (segment: TranscriptionSegment) => {
    if (segment.speakerLabel?.trim()) return segment.speakerLabel.trim();
    const number = Number(String(segment.speakerId || '').match(/(\d+)$/)?.[1] || 0);
    return number ? t('transcription.speakerName', {number}) : '';
  };

  const openSpeakerManager = () => {
    speakerNames.value = Object.fromEntries(
      completedSpeakers.value.map(speaker => [speaker.id, speaker.name]),
    );
    speakerMergeTargets.value = Object.fromEntries(
      completedSpeakers.value.map(speaker => [speaker.id, '']),
    );
    speakerDialogOpen.value = true;
  };

  const resolveSpeakerMergeTarget = (speakerId: string) => {
    const visited = new Set([speakerId]);
    let targetId = String(speakerMergeTargets.value[speakerId] || '').trim();
    while (targetId) {
      if (visited.has(targetId)) return '';
      visited.add(targetId);
      const next = String(speakerMergeTargets.value[targetId] || '').trim();
      if (!next) return targetId;
      targetId = next;
    }
    return speakerId;
  };

  const saveSpeakerChanges = async () => {
    const detail = state.completedDetail;
    if (!detail || speakerSaving.value) return;
    const speakerById = new Map(completedSpeakers.value.map(speaker => [speaker.id, speaker]));
    for (const speaker of completedSpeakers.value) {
      if (!resolveSpeakerMergeTarget(speaker.id)) {
        new Notice(t('transcription.speakerMergeCycle'));
        return;
      }
    }
    const updates = detail.segments.flatMap(segment => {
      const sourceId = String(segment.speakerId || '').trim();
      if (!sourceId) return [];
      const targetId = resolveSpeakerMergeTarget(sourceId);
      const target = speakerById.get(targetId);
      const label = String(speakerNames.value[targetId] || target?.name || '').trim();
      if (!label) return [];
      if (
        targetId === sourceId &&
        label === String(segment.speakerLabel || segmentSpeakerLabel(segment)).trim()
      ) {
        return [];
      }
      return [
        {
          id: segment.id,
          speakerId: targetId,
          speakerLabel: label,
          speakerSource: 'user' as const,
        },
      ];
    });
    if (!updates.length) {
      speakerDialogOpen.value = false;
      return;
    }
    speakerSaving.value = true;
    try {
      await controller.updateCompletedSpeakers(updates);
      speakerDialogOpen.value = false;
      new Notice(t('transcription.speakerSaved'));
    } catch (error: any) {
      new Notice(error?.message || t('transcription.speakerSaveFailed'));
    } finally {
      speakerSaving.value = false;
    }
  };

  const assignCompletedSpeaker = async (segment: TranscriptionSegment, speakerId: string) => {
    if (!speakerId || segment.speakerId === speakerId || assigningSpeakerSegmentId.value) return;
    const speaker = completedSpeakers.value.find(item => item.id === speakerId);
    if (!speaker) return;
    assigningSpeakerSegmentId.value = segment.id;
    try {
      await controller.updateCompletedSpeakers([
        {
          id: segment.id,
          speakerId,
          speakerLabel: speaker.name,
          speakerSource: 'user',
        },
      ]);
      new Notice(t('transcription.speakerAssigned'));
    } catch (error: any) {
      new Notice(error?.message || t('transcription.speakerSaveFailed'));
    } finally {
      assigningSpeakerSegmentId.value = '';
    }
  };

  const refreshActiveFile = (candidate = plugin.app.workspace.getActiveFile()) => {
    activeFile.value = candidate;
    const markdownFile =
      candidate instanceof TFile && candidate.extension === 'md' ? candidate : null;
    activeMarkdownPath.value = markdownFile?.path || '';
    return markdownFile;
  };

  const handleLiveWriteToggle = (enabled: boolean) => {
    if (!enabled) {
      form.value.liveWriteToNote = false;
      refreshActiveFile();
      return;
    }
    const currentNote = refreshActiveFile();
    if (!currentNote) {
      form.value.liveWriteToNote = false;
      new Notice(t('transcription.liveWriteNeedsNoteNotice'));
      return;
    }
    form.value.liveWriteToNote = true;
  };

  const loadSetup = async (requestMicrophonePermission = false) => {
    loading.value = true;
    setupStatus.value = 'checking';
    startOptions.value = null;
    try {
      const health = await plugin.api.health();
      if (!isTranscriptionVersionSupported(health.appVersion)) {
        setupStatus.value = 'unsupported';
        return false;
      }
      const options = await plugin.api.getTranscriptionStartOptions();
      startOptions.value = options;
      setupStatus.value = 'ready';
      if (
        !form.value.providerId ||
        !options.providers.some(item => item.id === form.value.providerId)
      ) {
        form.value.providerId = options.activeProviderId || options.providers[0]?.id || '';
      }

      try {
        const devices = await listAudioInputDevices(requestMicrophonePermission);
        audioDevices.value = devices;
        if (
          form.value.deviceId !== 'default' &&
          !devices.some(device => device.deviceId === form.value.deviceId)
        ) {
          form.value.deviceId = 'default';
        }
      } catch (error: any) {
        new Notice(error?.message || t('transcription.microphoneLoadFailed'));
        return false;
      }
      return true;
    } catch (error: unknown) {
      setupStatus.value = classifyTranscriptionAvailabilityError(error);
      return false;
    } finally {
      loading.value = false;
    }
  };

  const start = async () => {
    if (!canStart.value) return;
    const liveTargetFile = form.value.liveWriteToNote ? refreshActiveFile() : null;
    if (form.value.liveWriteToNote && !liveTargetFile) {
      form.value.liveWriteToNote = false;
      new Notice(t('transcription.liveWriteNeedsNoteNotice'));
      return;
    }
    starting.value = true;
    try {
      if (!form.value.title.trim() || form.value.title.trim() === autoGeneratedTitle) {
        autoGeneratedTitle = createDefaultRecordTitle();
        form.value.title = autoGeneratedTitle;
      }
      plugin.settings.transcription.defaultScene = form.value.scene;
      plugin.settings.transcription.defaultProviderId = form.value.providerId;
      plugin.settings.transcription.defaultMicrophoneId = form.value.deviceId;
      plugin.settings.transcription.saveAudio = form.value.saveAudio;
      await plugin.saveSettings();
      await controller.start({
        title: form.value.title.trim() || undefined,
        scenario: form.value.scene,
        providerId: form.value.providerId,
        deviceId: form.value.deviceId,
        saveAudio: form.value.saveAudio,
        speakerDiarization: form.value.speakerDiarization,
        speakerCount: Number(form.value.speakerCount || 0),
        targetPath: liveTargetFile?.path || activeMarkdownPath.value,
        liveWriteToNote: form.value.liveWriteToNote,
      });
    } catch (error: any) {
      new Notice(error?.message || t('transcription.startFailed'));
    } finally {
      starting.value = false;
    }
  };

  const runAction = async <T,>(action: () => Promise<T>) => {
    try {
      return await action();
    } catch (error: any) {
      new Notice(error?.message || t('transcription.actionFailed'));
      return undefined;
    }
  };

  const mark = async (kind: TranscriptionMarkKind) => {
    const marked = await runAction(() => controller.mark(kind));
    if (marked) {
      new Notice(
        t(
          kind === 'highlight'
            ? 'transcription.markHighlightSuccess'
            : 'transcription.markTodoSuccess',
        ),
      );
    }
  };

  const openAllRecords = async () => {
    if (openingRecords.value) return;
    openingRecords.value = true;
    try {
      const opened = await runAction(() => plugin.api.openTranscriptions());
      if (opened !== undefined) {
        new Notice(t('transcription.recordsOpened'));
      }
    } finally {
      openingRecords.value = false;
    }
  };
  const openCurrentRecord = () =>
    runAction(() =>
      plugin.api.openTranscriptions(state.completedDetail?.record.id || state.record?.id),
    );
  const openHistory = () => {
    historyItems.value = [...(plugin.settings.transcriptionHistory || [])].sort(
      (a, b) => b.createdAt - a.createdAt,
    );
    historyDialogOpen.value = true;
  };
  const showHistoryItem = (item: (typeof historyItems.value)[number]) => {
    if (!controller.showCachedHistory(item)) return;
    completionView.value = item.summary || item.keyPoints || item.todos ? 'summary' : 'transcript';
    historyDialogOpen.value = false;
  };
  const organizeCompletedRecord = async () => {
    if (organizing.value || hasGeneratedSummary.value || !hasCompletedTranscript.value) return;
    organizing.value = true;
    try {
      const result = await runAction(() => controller.organizeCompletedRecord());
      if (result) {
        completionView.value = 'summary';
        new Notice(t('transcription.summaryGenerated'));
      }
    } finally {
      organizing.value = false;
    }
  };
  const copyCompletedTranscript = async () => {
    if (!completedTranscript.value) return;
    await runAction(async () => {
      await navigator.clipboard.writeText(completedTranscript.value);
      new Notice(t('transcription.transcriptCopied'));
    });
  };
  const openLiveTargetNote = () =>
    runAction(() =>
      openObsidianNote(plugin.app, state.liveNoteTargetPath, {
        moved: t('transcription.targetMissing'),
        openFailed: t('transcription.openTargetNoteFailed'),
      }),
    );

  const handleStreamScroll = () => {
    const element = transcriptionStream.value;
    if (!element) return;
    followLatestSegment.value =
      element.scrollHeight - element.scrollTop - element.clientHeight < 80;
  };

  const scheduleScrollToLatest = () => {
    if (!isActive.value || !followLatestSegment.value) return;
    window.cancelAnimationFrame(streamScrollFrame);
    streamScrollFrame = window.requestAnimationFrame(() => {
      const element = transcriptionStream.value;
      if (!element || !isActive.value || !followLatestSegment.value) return;
      element.scrollTop = element.scrollHeight;
    });
  };

  const stopMicrophoneTest = (complete = false) => {
    window.clearTimeout(microphoneTestTimer);
    window.clearInterval(microphoneTestClock);
    microphoneTestTimer = 0;
    microphoneTestClock = 0;
    microphoneTestCapture?.stop();
    microphoneTestCapture = null;
    if (complete && microphoneTestStatus.value === 'recording') {
      microphoneTestStatus.value = 'complete';
    } else if (!complete && microphoneTestStatus.value === 'recording') {
      microphoneTestStatus.value = 'idle';
    }
    microphoneTestLevel.value = 0;
  };

  const startMicrophoneTest = async () => {
    stopMicrophoneTest();
    if (microphoneTestUrl.value) URL.revokeObjectURL(microphoneTestUrl.value);
    microphoneTestUrl.value = '';
    microphoneTestError.value = '';
    microphoneTestSeconds.value = 0;
    const chunks: Uint8Array[] = [];
    try {
      if (!(await loadSetup(true))) {
        microphoneTestStatus.value = 'error';
        microphoneTestError.value = t('transcription.microphoneTestFailed');
        return;
      }
      microphoneTestStatus.value = 'recording';
      microphoneTestCapture = await startAudioCapture({
        deviceId: form.value.deviceId,
        sampleRate: 16000,
        chunkMs: 100,
        onDeviceEnded: () => {
          microphoneTestError.value = t('transcription.microphoneErrors.unavailable');
          microphoneTestStatus.value = 'error';
          stopMicrophoneTest();
        },
        onChunk: (chunk, level) => {
          chunks.push(chunk.slice());
          microphoneTestLevel.value = level;
        },
      });
      microphoneTestClock = window.setInterval(() => {
        microphoneTestSeconds.value += 1;
      }, 1_000);
      microphoneTestTimer = window.setTimeout(() => {
        stopMicrophoneTest(true);
        microphoneTestUrl.value = URL.createObjectURL(pcm16ChunksToWavBlob(chunks));
      }, 5_000);
    } catch (error: any) {
      microphoneTestError.value = error?.message || t('transcription.microphoneTestFailed');
      microphoneTestStatus.value = 'error';
      stopMicrophoneTest();
    }
  };

  const reset = async () => {
    speakerDialogOpen.value = false;
    controller.reset();
    autoGeneratedTitle = createDefaultRecordTitle();
    form.value.title = autoGeneratedTitle;
    form.value.liveWriteToNote = false;
    completionView.value = 'transcript';
    await loadSetup(false);
  };

  watch(activeMarkdownPath, path => {
    if (!path) form.value.liveWriteToNote = false;
  });

  watch(currentProvider, provider => {
    if (!provider?.supportsSpeakerDiarization) {
      form.value.speakerDiarization = false;
      form.value.speakerCount = '0';
    }
  });

  watch(() => [state.segments.length, state.partialText] as const, scheduleScrollToLatest, {
    flush: 'post',
  });

  watch(
    () => state.status,
    status => {
      if (status === 'starting' || status === 'recording') {
        followLatestSegment.value = true;
      } else if (status === 'completed') {
        const recordId = state.completedDetail?.record.id || state.record?.id || '';
        if (recordId && recordId !== lastCompletionNoticeRecordId) {
          lastCompletionNoticeRecordId = recordId;
          new Notice(t('transcription.completedSavedNotice'), 7_000);
        }
        window.cancelAnimationFrame(streamScrollFrame);
        streamScrollFrame = window.requestAnimationFrame(() => {
          if (transcriptionStream.value) transcriptionStream.value.scrollTop = 0;
        });
      }
    },
    {flush: 'post'},
  );

  onMounted(() => {
    refreshActiveFile();
    const workspace = plugin.app.workspace as any;
    const vault = plugin.app.vault as any;
    const fileOpenRef = workspace.on?.('file-open', (file: TFile | null) => {
      refreshActiveFile(file || plugin.app.workspace.getActiveFile());
    });
    if (fileOpenRef) workspaceEventRefs.push(fileOpenRef);
    const leafChangeRef = workspace.on?.('active-leaf-change', () => refreshActiveFile());
    if (leafChangeRef) workspaceEventRefs.push(leafChangeRef);
    const renameRef = vault.on?.('rename', (file: TFile, oldPath: string) => {
      if (oldPath === activeMarkdownPath.value || file === activeFile.value) {
        refreshActiveFile(file);
      }
    });
    if (renameRef) vaultEventRefs.push(renameRef);
    void loadSetup(false);
  });

  onUnmounted(() => {
    stopMicrophoneTest();
    window.cancelAnimationFrame(streamScrollFrame);
    if (microphoneTestUrl.value) URL.revokeObjectURL(microphoneTestUrl.value);
    const workspace = plugin.app.workspace as any;
    const vault = plugin.app.vault as any;
    if (typeof workspace.offref === 'function') {
      workspaceEventRefs.forEach(eventRef => workspace.offref(eventRef));
    }
    if (typeof vault.offref === 'function') {
      vaultEventRefs.forEach(eventRef => vault.offref(eventRef));
    }
    workspaceEventRefs.splice(0);
    vaultEventRefs.splice(0);
  });
</script>

<template>
  <section class="wm-page wm-transcription-page" :class="{'is-session-view': usesFixedLayout}">
    <header class="wm-page-header">
      <div class="wm-title-line">
        <MicrophoneIcon class="wm-title-icon" />
        <div>
          <h2>{{ t('transcription.title') }}</h2>
          <p class="wm-muted">{{ t('transcription.subtitle') }}</p>
        </div>
      </div>
      <div class="wm-actions">
        <button class="wm-button" type="button" @click="openHistory">
          <ClockIcon class="wm-icon" />
          {{ t('transcription.history') }}
        </button>
        <button class="wm-button" type="button" :disabled="openingRecords" @click="openAllRecords">
          <span v-if="openingRecords" class="wm-loading-spinner"></span>
          <ListBulletIcon v-else class="wm-icon" />
          {{ openingRecords ? t('transcription.openingRecords') : t('transcription.viewAllRecords') }}
        </button>
      </div>
    </header>

    <template v-if="state.status === 'idle' && setupStatus !== 'ready'">
      <section class="wm-panel wm-transcription-compatibility">
        <span v-if="setupStatus === 'checking'" class="wm-loading-spinner"></span>
        <ExclamationTriangleIcon v-else class="wm-transcription-result-icon" />
        <div>
          <h3>{{ setupMessage.title }}</h3>
          <p class="wm-muted">{{ setupMessage.description }}</p>
        </div>
        <button
          v-if="setupStatus !== 'checking'"
          class="wm-button is-primary"
          type="button"
          :disabled="loading"
          @click="loadSetup(false)"
        >
          <ArrowPathIcon class="wm-icon" />
          {{ t('common.retry') }}
        </button>
      </section>
    </template>

    <template v-else-if="state.status === 'idle'">
      <section class="wm-panel wm-transcription-setup">
        <label>
          <span class="wm-setting-label">{{ t('transcription.recordTitle') }}</span>
          <input
            v-model="form.title"
            class="wm-input"
            :placeholder="t('transcription.recordTitlePlaceholder')"
          />
        </label>
        <div class="wm-field-row">
          <label>
            <span class="wm-setting-label">{{ t('transcription.scene') }}</span>
            <RekaSelect v-model="form.scene" :options="sceneOptions" />
          </label>
          <label>
            <span class="wm-setting-label">
              <span>{{ t('transcription.provider') }}</span>
              <small
                v-if="startOptions && providerOptions.length === 0"
                class="wm-provider-setup-hint"
              >
                {{ t('transcription.providerSetupHint') }}
              </small>
            </span>
            <RekaSelect
              v-model="form.providerId"
              :options="providerOptions"
              :placeholder="t('transcription.chooseProvider')"
            />
          </label>
        </div>
        <label>
          <span class="wm-setting-label">{{ t('transcription.microphone') }}</span>
          <div class="wm-transcription-device-row">
            <RekaSelect
              v-model="form.deviceId"
              :options="microphoneOptions"
              :placeholder="t('transcription.chooseMicrophone')"
            />
            <button class="wm-button" type="button" :disabled="loading" @click="loadSetup(true)">
              <ArrowPathIcon class="wm-icon" />
              {{ t('common.refresh') }}
            </button>
          </div>
        </label>
        <div class="wm-transcription-options">
          <div class="wm-toggle-row">
            <span class="wm-toggle-copy">
              <strong>{{ t('transcription.saveAudio') }}</strong>
              <small class="wm-muted">{{ t('transcription.saveAudioDesc') }}</small>
            </span>
            <RekaSwitch v-model="form.saveAudio" :aria-label="t('transcription.saveAudio')" />
          </div>
          <div v-if="currentProvider?.supportsSpeakerDiarization" class="wm-toggle-row">
            <span class="wm-toggle-copy">
              <strong>{{ t('transcription.speakerDiarization') }}</strong>
              <small class="wm-muted">
                {{
                  startOptions?.membership.canUseSpeakerDiarization
                    ? t('transcription.speakerDiarizationDesc')
                    : t('transcription.speakerDiarizationUnavailable')
                }}
              </small>
            </span>
            <RekaSwitch
              v-model="form.speakerDiarization"
              :disabled="!startOptions?.membership.canUseSpeakerDiarization"
              :aria-label="t('transcription.speakerDiarization')"
            />
          </div>
          <label
            v-if="currentProvider?.supportsSpeakerDiarization && form.speakerDiarization"
            class="wm-transcription-speaker-count"
          >
            <span class="wm-setting-label">{{ t('transcription.speakerCount') }}</span>
            <RekaSelect v-model="form.speakerCount" :options="speakerCountOptions" />
          </label>
          <div class="wm-toggle-row">
            <span class="wm-toggle-copy">
              <strong>{{ t('transcription.liveWriteToNote') }}</strong>
              <small class="wm-muted">
                {{
                  activeMarkdownPath
                    ? t('transcription.liveWriteToNoteDesc')
                    : t('transcription.liveWriteNeedsNote')
                }}
              </small>
              <span
                v-if="form.liveWriteToNote && activeMarkdownPath"
                class="wm-transcription-target"
              >
                <DocumentArrowDownIcon class="wm-icon" />
                <span>{{ t('transcription.liveWriteTarget', {path: activeMarkdownPath}) }}</span>
              </span>
            </span>
            <RekaSwitch
              :model-value="form.liveWriteToNote"
              :aria-label="t('transcription.liveWriteToNote')"
              @update:model-value="handleLiveWriteToggle"
            />
          </div>
        </div>
      </section>

      <section class="wm-panel wm-microphone-test">
        <div class="wm-panel-title">
          <SignalIcon class="wm-panel-title-icon" />
          <h3>{{ t('transcription.testRecording') }}</h3>
        </div>
        <p class="wm-muted">{{ t('transcription.testRecordingDesc') }}</p>
        <div v-if="microphoneTestStatus === 'recording'" class="wm-audio-level">
          <span :style="{width: `${Math.max(3, microphoneTestLevel * 100)}%`}"></span>
        </div>
        <p v-if="microphoneTestStatus === 'recording'" class="wm-muted">
          {{
            t('transcription.testingRecording', {seconds: Math.min(5, microphoneTestSeconds + 1)})
          }}
        </p>
        <p v-if="microphoneTestError" class="wm-inline-error">{{ microphoneTestError }}</p>
        <audio
          v-if="microphoneTestUrl"
          class="wm-test-audio"
          :src="microphoneTestUrl"
          controls
        ></audio>
        <footer class="wm-actions">
          <button
            v-if="microphoneTestStatus !== 'recording'"
            class="wm-button"
            type="button"
            :disabled="isActive"
            @click="startMicrophoneTest"
          >
            <MicrophoneIcon class="wm-icon" />
            {{ microphoneTestUrl ? t('transcription.testAgain') : t('transcription.startTest') }}
          </button>
          <button v-else class="wm-button" type="button" @click="stopMicrophoneTest(false)">
            <StopIcon class="wm-icon" />
            {{ t('common.stop') }}
          </button>
        </footer>
      </section>

      <div class="wm-transcription-start-actions">
        <span v-if="startOptions && !startOptions.providers.length" class="wm-inline-error">
          {{ t('transcription.noProvider') }}
        </span>
        <button
          class="wm-button is-primary wm-transcription-start-button"
          type="button"
          :disabled="!canStart"
          @click="start"
        >
          <span v-if="starting" class="wm-loading-spinner"></span>
          <MicrophoneIcon v-else class="wm-icon" />
          {{ starting ? t('transcription.starting') : t('transcription.start') }}
        </button>
      </div>
    </template>

    <template v-else-if="isActive">
      <div class="wm-transcription-live-header">
        <div class="wm-recording-status">
          <span class="wm-record-dot" :class="{'is-paused': isPaused}"></span>
          <strong>{{ statusLabel }}</strong>
          <span>{{ elapsed }}</span>
        </div>
        <div class="wm-transcription-connection">
          <SignalIcon class="wm-icon" />
          <span>{{ connectionLabel }}</span>
        </div>
      </div>

      <div class="wm-audio-level">
        <span :style="{width: `${Math.max(2, state.audioLevel * 100)}%`}"></span>
      </div>

      <section
        ref="transcriptionStream"
        class="wm-transcription-stream"
        aria-live="polite"
        @scroll.passive="handleStreamScroll"
      >
        <article
          v-for="segment in state.segments"
          :key="segment.id"
          v-memo="[
            segment.id,
            segment.text,
            segment.beginTimeMs,
            segment.speakerId,
            segment.speakerLabel,
          ]"
          class="wm-transcription-segment"
        >
          <time>{{ formatDuration(segment.beginTimeMs || 0) }}</time>
          <div class="wm-transcription-segment-content">
            <span v-if="segmentSpeakerLabel(segment)" class="wm-transcription-speaker">
              {{ segmentSpeakerLabel(segment) }}
            </span>
            <p>{{ segment.text }}</p>
          </div>
        </article>
        <article v-if="state.partialText" class="wm-transcription-segment is-partial">
          <time>{{ elapsed }}</time>
          <p>{{ state.partialText }}</p>
        </article>
        <div v-if="!state.segments.length && !state.partialText" class="wm-transcription-empty">
          <MicrophoneIcon class="wm-title-icon" />
          <p>{{ t('transcription.waitingSpeech') }}</p>
        </div>
      </section>

      <p class="wm-transcription-saved-hint">
        <CheckCircleIcon class="wm-icon" />
        {{ t('transcription.savingToWiseMind') }}
      </p>

      <div
        v-if="state.liveNoteWriteStatus !== 'idle'"
        class="wm-transcription-live-note"
        :class="{'is-error': state.liveNoteWriteStatus === 'error'}"
      >
        <ExclamationTriangleIcon v-if="state.liveNoteWriteStatus === 'error'" class="wm-icon" />
        <DocumentArrowDownIcon v-else class="wm-icon" />
        <span>
          {{
            state.liveNoteWriteStatus === 'error'
              ? t('transcription.liveWriteFailedInline')
              : t('transcription.liveWritingTo', {path: state.liveNoteTargetPath})
          }}
        </span>
        <button
          v-if="state.liveNoteTargetPath"
          class="wm-button"
          type="button"
          @click="openLiveTargetNote"
        >
          <DocumentArrowDownIcon class="wm-icon" />
          {{ t('transcription.openTargetNote') }}
        </button>
      </div>

      <footer class="wm-transcription-controls">
        <div class="wm-actions">
          <button
            v-if="isRecording"
            class="wm-button"
            type="button"
            @click="runAction(() => controller.pause())"
          >
            <PauseIcon class="wm-icon" />
            {{ t('transcription.pause') }}
          </button>
          <button
            v-else-if="isPaused"
            class="wm-button"
            type="button"
            @click="runAction(() => controller.resume())"
          >
            <PlayIcon class="wm-icon" />
            {{ t('transcription.resume') }}
          </button>
          <button
            v-if="state.status === 'stopping' && state.error"
            class="wm-button"
            type="button"
            @click="runAction(() => controller.retryCompletion())"
          >
            <ArrowPathIcon class="wm-icon" />
            {{ t('transcription.retryResult') }}
          </button>
          <button
            class="wm-button"
            type="button"
            :disabled="!isRecording && !isPaused"
            @click="mark('highlight')"
          >
            <SparklesIcon class="wm-icon" />
            {{ t('transcription.markHighlight') }}
          </button>
          <button
            class="wm-button"
            type="button"
            :disabled="!isRecording && !isPaused"
            @click="mark('todo')"
          >
            <Square2StackIcon class="wm-icon" />
            {{ t('transcription.markTodo') }}
          </button>
        </div>
        <button
          class="wm-button is-danger"
          type="button"
          :disabled="state.status === 'stopping'"
          @click="runAction(() => controller.stop())"
        >
          <StopIcon class="wm-icon" />
          {{ state.status === 'stopping' ? t('transcription.stopping') : t('transcription.stop') }}
        </button>
      </footer>
      <p v-if="state.error" class="wm-inline-error">{{ state.error }}</p>
    </template>

    <template v-else-if="state.status === 'completed' && state.completedDetail">
      <section class="wm-panel wm-transcription-complete">
        <CheckCircleIcon class="wm-transcription-result-icon" />
        <div>
          <h3>{{ t('transcription.completed') }}</h3>
          <p class="wm-muted">
            {{
              t('transcription.completedDesc', {
                duration: formatDuration(state.completedDetail.record.durationMs),
                count: state.completedDetail.record.wordCount,
              })
            }}
          </p>
        </div>
        <button class="wm-button is-primary" type="button" @click="reset">
          <MicrophoneIcon class="wm-icon" />
          {{ t('transcription.newRecording') }}
        </button>
      </section>
      <div
        class="wm-transcription-result-tabs"
        role="tablist"
        :aria-label="t('transcription.resultViews')"
      >
        <button
          class="wm-transcription-result-tab"
          :class="{'is-active': completionView === 'transcript'}"
          type="button"
          role="tab"
          :aria-selected="completionView === 'transcript'"
          @click="completionView = 'transcript'"
        >
          {{ t('transcription.transcriptView') }}
        </button>
        <button
          class="wm-transcription-result-tab"
          :class="{'is-active': completionView === 'summary'}"
          type="button"
          role="tab"
          :aria-selected="completionView === 'summary'"
          @click="completionView = 'summary'"
        >
          {{
            t(
              hasGeneratedSummary
                ? 'transcription.summaryView'
                : 'transcription.generateSummary',
            )
          }}
        </button>
      </div>
      <div
        v-if="completionView === 'transcript' && completedSpeakers.length"
        class="wm-transcription-speaker-toolbar"
      >
        <span>
          <UserGroupIcon class="wm-icon" />
          {{ t('transcription.identifiedSpeakers', {count: completedSpeakers.length}) }}
        </span>
        <button class="wm-button" type="button" @click="openSpeakerManager">
          <UserGroupIcon class="wm-icon" />
          {{ t('transcription.manageSpeakers') }}
        </button>
      </div>
      <section
        v-if="completionView === 'transcript'"
        ref="transcriptionStream"
        class="wm-transcription-stream is-complete"
        @scroll.passive="handleStreamScroll"
      >
        <article
          v-for="segment in state.completedDetail.segments"
          :key="segment.id"
          v-memo="[
            segment.id,
            segment.text,
            segment.beginTimeMs,
            segment.speakerId,
            segment.speakerLabel,
          ]"
          class="wm-transcription-segment"
        >
          <time>{{ formatDuration(segment.beginTimeMs || 0) }}</time>
          <div class="wm-transcription-segment-content">
            <select
              v-if="segmentSpeakerLabel(segment) && completedSpeakers.length"
              class="wm-transcription-speaker-select"
              :value="segment.speakerId"
              :aria-label="t('transcription.selectSpeaker')"
              :disabled="Boolean(assigningSpeakerSegmentId)"
              @change="
                assignCompletedSpeaker(
                  segment,
                  ($event.target as HTMLSelectElement).value,
                )
              "
            >
              <option v-for="speaker in completedSpeakers" :key="speaker.id" :value="speaker.id">
                {{ speaker.name }}
              </option>
            </select>
            <span v-else-if="segmentSpeakerLabel(segment)" class="wm-transcription-speaker">
              {{ segmentSpeakerLabel(segment) }}
            </span>
            <p>{{ segment.text }}</p>
          </div>
        </article>
      </section>
      <section v-else class="wm-transcription-summary-view">
        <div v-if="!hasGeneratedSummary" class="wm-transcription-summary-empty">
          <SparklesIcon class="wm-transcription-result-icon" />
          <h3>{{ t('transcription.summaryEmptyTitle') }}</h3>
          <p class="wm-muted">
            {{
              hasCompletedTranscript
                ? t('transcription.summaryEmptyDesc')
                : t('transcription.summaryNeedsTranscript')
            }}
          </p>
          <button
            class="wm-button is-primary"
            type="button"
            :disabled="organizing || !hasCompletedTranscript"
            @click="organizeCompletedRecord"
          >
            <span v-if="organizing" class="wm-loading-spinner"></span>
            <SparklesIcon v-else class="wm-icon" />
            {{ organizing ? t('transcription.generatingSummary') : t('transcription.generateSummary') }}
          </button>
        </div>
        <template v-else>
          <article class="wm-transcription-summary-section">
            <h3>{{ t('transcription.noteSections.summary') }}</h3>
            <MarkdownView :markdown="state.completedDetail.record.summary || ''" />
          </article>
          <article v-if="state.completedDetail.record.keyPoints" class="wm-transcription-summary-section">
            <h3>{{ t('transcription.noteSections.keyPoints') }}</h3>
            <MarkdownView :markdown="state.completedDetail.record.keyPoints" />
          </article>
          <article v-if="state.completedDetail.record.todos" class="wm-transcription-summary-section">
            <h3>{{ t('transcription.noteSections.todos') }}</h3>
            <MarkdownView :markdown="state.completedDetail.record.todos" />
          </article>
        </template>
      </section>
      <div class="wm-transcription-complete-footer">
        <div class="wm-transcription-saved-callout">
          <CheckCircleIcon class="wm-icon" />
          <span>
            <strong>{{ t('transcription.savedToWiseMind') }}</strong>
            <small>{{ t('transcription.savedToWiseMindDesc') }}</small>
          </span>
        </div>
        <footer class="wm-transcription-complete-actions">
          <div class="wm-actions">
            <button
              class="wm-button"
              type="button"
              :disabled="!completedTranscript"
              @click="copyCompletedTranscript"
            >
              <ClipboardDocumentIcon class="wm-icon" />
              {{ t('transcription.copyTranscript') }}
            </button>
            <button
              class="wm-button"
              type="button"
              :disabled="!activeMarkdownPath || isCurrentNoteAlreadyWritten"
              @click="runAction(() => controller.insertIntoTargetNote(activeMarkdownPath))"
            >
              <CheckCircleIcon v-if="isCurrentNoteAlreadyWritten" class="wm-icon" />
              <DocumentArrowDownIcon v-else class="wm-icon" />
              {{
                t(
                  isCurrentNoteAlreadyWritten
                    ? 'transcription.alreadyInsertedCurrentNote'
                    : 'transcription.insertCurrentNote',
                )
              }}
            </button>
            <button
              class="wm-button"
              type="button"
              @click="runAction(() => controller.saveAsNewNote())"
            >
              <DocumentPlusIcon class="wm-icon" />
              {{ t('transcription.saveNewNote') }}
            </button>
            <button class="wm-button" type="button" @click="openCurrentRecord">
              <ListBulletIcon class="wm-icon" />
              {{ t('transcription.openInWiseMind') }}
            </button>
          </div>
        </footer>
      </div>
    </template>

    <template v-else-if="state.status === 'error'">
      <section class="wm-panel wm-transcription-error">
        <ExclamationTriangleIcon class="wm-transcription-result-icon" />
        <div>
          <h3>{{ t('transcription.failed') }}</h3>
          <p>{{ state.error }}</p>
        </div>
      </section>
      <footer class="wm-actions wm-transcription-error-actions">
        <button class="wm-button" type="button" @click="openCurrentRecord">
          <ListBulletIcon class="wm-icon" />
          {{ t('transcription.viewSavedRecord') }}
        </button>
        <button class="wm-button is-primary" type="button" @click="reset">
          <ArrowPathIcon class="wm-icon" />
          {{ t('common.retry') }}
        </button>
      </footer>
    </template>

    <WmDialog
      v-model:open="speakerDialogOpen"
      :title="t('transcription.manageSpeakers')"
      :description="t('transcription.manageSpeakersDesc')"
      content-class="wm-transcription-speaker-dialog"
    >
      <div class="wm-transcription-speaker-list">
        <div
          v-for="speaker in completedSpeakers"
          :key="speaker.id"
          class="wm-transcription-speaker-row"
        >
          <span class="wm-transcription-speaker-avatar" aria-hidden="true">
            <UserGroupIcon />
          </span>
          <label class="wm-transcription-speaker-field">
            <span>{{ t('transcription.speakerDisplayName') }}</span>
            <input
              v-model.trim="speakerNames[speaker.id]"
              class="wm-input"
              type="text"
              maxlength="40"
              :placeholder="speaker.name"
              :disabled="Boolean(speakerMergeTargets[speaker.id]) || speakerSaving"
            />
            <small>
              {{
                t('transcription.speakerSegmentStats', {
                  count: speaker.segmentCount,
                  duration: formatDuration(speaker.durationMs),
                })
              }}
            </small>
          </label>
          <label class="wm-transcription-speaker-field is-merge">
            <span>{{ t('transcription.mergeSpeakerInto') }}</span>
            <select v-model="speakerMergeTargets[speaker.id]" :disabled="speakerSaving">
              <option value="">{{ t('transcription.keepSpeakerSeparate') }}</option>
              <option
                v-for="target in completedSpeakers.filter(item => item.id !== speaker.id)"
                :key="target.id"
                :value="target.id"
              >
                {{ speakerNames[target.id] || target.name }}
              </option>
            </select>
          </label>
        </div>
      </div>
      <footer class="wm-dialog-actions wm-actions">
        <button
          class="wm-button"
          type="button"
          :disabled="speakerSaving"
          @click="speakerDialogOpen = false"
        >
          <XMarkIcon class="wm-icon" />
          {{ t('common.cancel') }}
        </button>
        <button
          class="wm-button is-primary"
          type="button"
          :disabled="speakerSaving"
          @click="saveSpeakerChanges"
        >
          <ArrowPathIcon v-if="speakerSaving" class="wm-icon wm-spin" />
          <CheckIcon v-else class="wm-icon" />
          {{ t('transcription.saveSpeakers') }}
        </button>
      </footer>
    </WmDialog>

    <WmDialog
      v-model:open="historyDialogOpen"
      :title="t('transcription.historyTitle')"
      :description="t('transcription.historyDesc')"
      content-class="wm-transcription-history-dialog"
    >
      <div v-if="historyItems.length" class="wm-transcription-history-list">
        <button
          v-for="item in historyItems"
          :key="item.id"
          class="wm-transcription-history-item"
          type="button"
          :disabled="isActive"
          @click="showHistoryItem(item)"
        >
          <span class="wm-transcription-history-icon" aria-hidden="true">
            <MicrophoneIcon />
          </span>
          <span class="wm-transcription-history-content">
            <span class="wm-transcription-history-heading">
              <strong>{{ item.title }}</strong>
              <span class="wm-transcription-history-kind">
                {{
                  item.summary
                    ? t('transcription.summaryView')
                    : t('transcription.transcriptView')
                }}
              </span>
            </span>
            <small class="wm-transcription-history-meta">
              {{ formatRecordDate(item.createdAt) }} · {{ formatDuration(item.durationMs) }} ·
              {{ t('transcription.historyWordCount', {count: item.wordCount}) }}
            </small>
          </span>
          <ChevronRightIcon class="wm-transcription-history-chevron" aria-hidden="true" />
        </button>
      </div>
      <div v-else class="wm-transcription-history-empty">
        <ClockIcon class="wm-transcription-result-icon" />
        <p>{{ t('transcription.historyEmpty') }}</p>
      </div>
    </WmDialog>
  </section>
</template>
